on:
  pull_request:
    branches:
      - main
name: PR Workflow
jobs:
  validate_identities:
    name: Identity Schema Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - run: go run main.go
